package com.ids.api;

import jakarta.persistence.*;

/**
 * JPA entity that maps one alert to a row in the `alerts` table.
 * The schema is created/updated automatically by Hibernate on startup.
 */
@Entity
@Table(name = "alerts", indexes = {
        @Index(name = "idx_severity",   columnList = "severity"),
        @Index(name = "idx_alert_type", columnList = "alertType"),
        @Index(name = "idx_timestamp",  columnList = "timestamp")
})
public class AlertEntity {

    /** UUID-based ID already generated by each detector (e.g. "SYN_3f7a1c2b"). */
    @Id
    @Column(name = "alert_id", nullable = false, length = 64)
    private String alertId;

    @Column(name = "detector_name", nullable = false, length = 64)
    private String detectorName;

    @Column(name = "severity", nullable = false, length = 16)
    private String severity;

    @Column(name = "alert_type", nullable = false, length = 64)
    private String alertType;

    @Column(name = "source_ip", length = 45)      // 45 = max IPv6 length
    private String sourceIP;

    @Column(name = "source_port")
    private int sourcePort;

    @Column(name = "destination_ip", length = 45)
    private String destinationIP;

    @Column(name = "destination_port")
    private int destinationPort;

    @Column(name = "protocol", length = 16)
    private String protocol;

    @Column(name = "message", length = 512)
    private String message;

    /** Unix epoch millis — easy to sort and convert on the frontend. */
    @Column(name = "timestamp", nullable = false)
    private long timestamp;

    // ── JPA requires a no-arg constructor ─────────────────────────
    protected AlertEntity() {}

    /** Convert an AlertDto → AlertEntity for persistence. */
    public static AlertEntity fromDto(AlertDto dto) {
        AlertEntity e = new AlertEntity();
        e.alertId        = dto.getAlertId();
        e.detectorName   = dto.getDetectorName();
        e.severity       = dto.getSeverity();
        e.alertType      = dto.getAlertType();
        e.sourceIP       = dto.getSourceIP();
        e.sourcePort     = dto.getSourcePort();
        e.destinationIP  = dto.getDestinationIP();
        e.destinationPort = dto.getDestinationPort();
        e.protocol       = dto.getProtocol();
        e.message        = dto.getMessage();
        e.timestamp      = dto.getTimestamp();
        return e;
    }

    /** Convert an AlertEntity → AlertDto for the REST API / WebSocket. */
    public AlertDto toDto() {
        return new AlertDto(
                alertId, detectorName, severity, alertType,
                sourceIP, sourcePort, destinationIP, destinationPort,
                protocol, message, timestamp
        );
    }

    // ── Getters ───────────────────────────────────────────────────
    public String getAlertId()        { return alertId; }
    public String getDetectorName()   { return detectorName; }
    public String getSeverity()       { return severity; }
    public String getAlertType()      { return alertType; }
    public String getSourceIP()       { return sourceIP; }
    public int    getSourcePort()     { return sourcePort; }
    public String getDestinationIP()  { return destinationIP; }
    public int    getDestinationPort(){ return destinationPort; }
    public String getProtocol()       { return protocol; }
    public String getMessage()        { return message; }
    public long   getTimestamp()      { return timestamp; }
}
