package com.ids.detection;

import com.ids.model.AlertEvent;
import com.ids.model.PacketData;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CopyOnWriteArrayList;

public class DetectionEngine {
    private final List<Detector> detectors;

    public DetectionEngine() {
        this.detectors = new CopyOnWriteArrayList<>();
        // Initialize default detectors
        this.detectors.add(new SynScanDetector());
        this.detectors.add(new IcmpFloodDetector());
        this.detectors.add(new RiskyPortDetector());
    }

    /**
     * Create a custom DetectionEngine with provided detectors.
     *
     * @param customDetectors list of detectors to use
     */
    public DetectionEngine(List<Detector> customDetectors) {
        this.detectors = new CopyOnWriteArrayList<>(customDetectors);
    }

    /**
     * Analyzes a packet using all registered detectors.
     *
     * @param packet the packet to analyze
     * @return list of alerts generated by detectors (empty if no threats detected)
     */
    public List<AlertEvent> analyze(PacketData packet) {
        if (packet == null) {
            return new ArrayList<>();
        }

        List<AlertEvent> alerts = new ArrayList<>();

        for (Detector detector : detectors) {
            try {
                Optional<AlertEvent> alert = detector.detect(packet);
                alert.ifPresent(alerts::add);
            } catch (Exception e) {
                System.err.printf("[ERROR] Detector %s failed: %s%n", detector.getName(), e.getMessage());
            }
        }

        return alerts;
    }

    /**
     * Analyzes multiple packets and aggregates all alerts.
     *
     * @param packets list of packets to analyze
     * @return list of all alerts generated
     */
    public List<AlertEvent> analyzePackets(List<PacketData> packets) {
        if (packets == null || packets.isEmpty()) {
            return new ArrayList<>();
        }

        List<AlertEvent> allAlerts = new ArrayList<>();

        for (PacketData packet : packets) {
            allAlerts.addAll(analyze(packet));
        }

        return allAlerts;
    }

    /**
     * Add a new detector to the engine.
     *
     * @param detector the detector to add
     */
    public void addDetector(Detector detector) {
        if (detector != null) {
            detectors.add(detector);
        }
    }

    /**
     * Remove a detector from the engine.
     *
     * @param detector the detector to remove
     */
    public void removeDetector(Detector detector) {
        if (detector != null) {
            detectors.remove(detector);
        }
    }

    /**
     * Get list of all active detectors.
     *
     * @return copy of detectors list
     */
    public List<Detector> getDetectors() {
        return new ArrayList<>(detectors);
    }

    /**
     * Get number of active detectors.
     *
     * @return count of detectors
     */
    public int getDetectorCount() {
        return detectors.size();
    }
}
